site_name: Портфолио
site_description: Портфолио специалиста разработки технической документации и Docs-as-Code
site_author: Васильняк Никита

# Copyright в футере
copyright: Copyright &copy; 2026 <br> <a href="https://t.me/nikita_vasilnyak"> <svg xmlns="http://www.w3.org/2000/svg" height="12" width="12" viewBox="0 0 512 512"><!--!Font Awesome Free v7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path fill="#d7f0f9" d="M256 8a248 248 0 1 0 0 496 248 248 0 1 0 0-496zM371 176.7c-3.7 39.2-19.9 134.4-28.1 178.3-3.5 18.6-10.3 24.8-16.9 25.4-14.4 1.3-25.3-9.5-39.3-18.7-21.8-14.3-34.2-23.2-55.3-37.2-24.5-16.1-8.6-25 5.3-39.5 3.7-3.8 67.1-61.5 68.3-66.7 .2-.7 .3-3.1-1.2-4.4s-3.6-.8-5.1-.5c-2.2 .5-37.1 23.5-104.6 69.1-9.9 6.8-18.9 10.1-26.9 9.9-8.9-.2-25.9-5-38.6-9.1-15.5-5-27.9-7.7-26.8-16.3 .6-4.5 6.7-9 18.4-13.7 72.3-31.5 120.5-52.3 144.6-62.3 68.9-28.6 83.2-33.6 92.5-33.8 2.1 0 6.6 .5 9.6 2.9 2 1.7 3.2 4.1 3.5 6.7 .5 3.2 .6 6.5 .4 9.8z"/></svg> Nikita Vasilnyak</a>

theme:
  name: material
  logo: assets/image/logo.svg
  favicon: assets/image/logo.svg
  font:
    text: Roboto # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода
  language: ru

  palette:
    # Настройки своей цветовой схемы
    - scheme: my-scheme

  features:
    # - navigation.sections # Добавление разделов верхнего уровня в боковом меню, отключение спойлеров в боковом меню
    - navigation.path # Хлебные крошки
    - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
    - navigation.tabs # Верхнее меню
    - navigation.tabs.sticky # Фиксация верхнего меню
    #- navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    #- toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.instant # Функция быстрой загрузки страниц
    - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest # Подсказки при вводе поискового запроса
    - search.highlight # Подсветка результатов поиска в тексте страницы
    - content.code.copy # Кнопка копирования в блоке кода

nav: # Структура сайта
  - Обо мне: index.md
  - Портфолио: # Раздел с выпадающим списком
      - portfolio/index.md
  - Курс Docs-as-Code:
      - course-dac/index.md
      - Инструкция для Telegram: course-dac/tasks/telegram-scenario.md
      - Примеры доки приложения Нотсапп:
          - Спецификация: course-dac/tasks/specification.md
          - Сценарий "Редактирование заметки": course-dac/tasks/edit-note.md
          - Диаграмма "Редактирование заметки": course-dac/tasks/plant-uml.md
          - API Specification Swagger: course-dac/tasks/api-swagger.md
          - API Specification Redoc: course-dac/tasks/api-redoc.md

markdown_extensions:
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.superfences # Поддержка вложенных блоков кода
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - pymdownx.blocks.caption # Подрисуночная подпись и центрирование
  - pymdownx.snippets # Сниппет
  - pymdownx.tabbed: # Использование вкладок (табов)
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Иконки и эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# INHERIT: "mkdocs.yml"
plugins:
  - search
  - glightbox # Для красивых галерей скриншотов
  - swagger-ui-tag
  - redoc-tag
  - link-embeds: # https://aetherinox.github.io/mkdocs-link-embeds/setup/install/ - полезная ссылка
      enabled: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        enabled: false
  - include-markdown

extra:
  generator: false # Убирает "Made with MkDocs"

extra_css:
  - stylesheets/link-embeds.css
  - stylesheets/extra.css
